[tool.poetry]
name = "lang-chain-qa"
authors = ["Marek Grzenkowicz <marek.grzenkowicz@roche.com>"]
description = ""
readme = "README.md"
version = "0.1.0"

[tool.poetry.dependencies]
python = "^3.10"

# LangChain
langchain = {version = "0.0.286", extras = ["llms"]}  # for a list of `llms` extras, see https://github.com/langchain-ai/langchain/blob/master/libs/langchain/pyproject.toml#L229
torch = ">=2.0.0, !=2.0.1"  # workaround for "libcublas.so.*[0-9] not found in the system path", https://stackoverflow.com/a/76647180/95

# model quantization
bitsandbytes = "0.41.1"

# loading and indexing documents for RAG
chromadb = "0.4.9"
pysqlite3-binary = "0.5.1"
sentence-transformers = "2.2.2"
wikipedia = "1.4.0"

# word embeddings
spacy = "3.6.1"
en_core_web_md = { url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_md-3.6.0/en_core_web_md-3.6.0.tar.gz" }

# Jupyter (v6, because v7 does not work well with RISE yet)
ipywidgets = "8.1.0"
jupyter-contrib-nbextensions = "0.7.0"
notebook = "6.5.5"
rise = "5.7.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
